[project]
name = "day05"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12, <4.0"
dependencies = [
    "tqdm>=4.67.1",
]

[tool.pytest.ini_options]
python_files = "*.py"
